### ISSUE TITLE
Note upcoming changes for "phase 3"

### ISSUE THREAD

**Issue by matthewHuiCsc** [relateiq/popgun#19]
Some things to note, 

1. clean up _listenForScroll. Could possibly be a single listener instead of adding and removing them on pop show/hide.
2. Modularize more of the code for reusability and ease of understanding.
3. Create Wiki to document architecture.
3. ??
4. Profit.

**Comment by danyaal** [comment]
wooo and we can use this system for closing issues?
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by matthewHuiCsc** [comment]
ohhh that's sick! i love it
